//
// Code auto-generated by Ray.
// Fri Mar 27 16:38:52 EDT 2026
//
package patrick.plugin;
import charlie.card.Card;
import charlie.shoe.Shoe01;
public class BotShoe01 extends Shoe01 {
  @Override
  public void init() {
    cards.clear();
    // Game G1 {5,5,5}: Huey K+6+2 | You 10+5+4 | Dewey 10+10 | Dealer K+7 >> Win{5}, Win{5}, Win{5}
    // Round 1
    // Huey
    cards.add(new Card(Card.KING, Card.Suit.DIAMONDS));
    // You
    cards.add(new Card(10, Card.Suit.DIAMONDS));
    // Dewey
    cards.add(new Card(10, Card.Suit.SPADES));
    // Dealer
    cards.add(new Card(Card.KING, Card.Suit.SPADES));
    // Round 2
    // Huey
    cards.add(new Card(6, Card.Suit.SPADES));
    // You
    cards.add(new Card(5, Card.Suit.CLUBS));
    // Dewey
    cards.add(new Card(10, Card.Suit.SPADES));
    // Dealer
    cards.add(new Card(7, Card.Suit.CLUBS));
    // Huey
    // Hitting
    cards.add(new Card(2, Card.Suit.DIAMONDS));
    // You
    // Hitting
    cards.add(new Card(4, Card.Suit.DIAMONDS));
    // Game G2 {5,5,5}: Huey 6+5+2 | You 10+5 | Dewey 10+3 | Dealer A+5+2 >> Lose{10}, Lose{5}, Lose{5}
    // Round 1
    // Huey
    cards.add(new Card(6, Card.Suit.HEARTS));
    // You
    cards.add(new Card(10, Card.Suit.HEARTS));
    // Dewey
    cards.add(new Card(10, Card.Suit.CLUBS));
    // Dealer
    cards.add(new Card(Card.ACE, Card.Suit.SPADES));
    // Round 2
    // Huey
    cards.add(new Card(5, Card.Suit.CLUBS));
    // You
    cards.add(new Card(5, Card.Suit.CLUBS));
    // Dewey
    cards.add(new Card(3, Card.Suit.HEARTS));
    // Dealer
    cards.add(new Card(5, Card.Suit.HEARTS));
    // Huey
    // Hitting
    cards.add(new Card(2, Card.Suit.SPADES));
    // Dealer
    // Hitting
    cards.add(new Card(2, Card.Suit.CLUBS));
    // Game G3 {5,5,5}: Huey 6+5+8 | You J+8 | Dewey 10+3+6 | Dealer 7+7+3 >> Win{5}, Win{5}, Win{10}
    // Round 1
    // Huey
    cards.add(new Card(6, Card.Suit.HEARTS));
    // You
    cards.add(new Card(Card.JACK, Card.Suit.CLUBS));
    // Dewey
    cards.add(new Card(10, Card.Suit.CLUBS));
    // Dealer
    cards.add(new Card(7, Card.Suit.HEARTS));
    // Round 2
    // Huey
    cards.add(new Card(5, Card.Suit.CLUBS));
    // You
    cards.add(new Card(8, Card.Suit.CLUBS));
    // Dewey
    cards.add(new Card(3, Card.Suit.SPADES));
    // Dealer
    cards.add(new Card(7, Card.Suit.CLUBS));
    // Huey
    // Hitting
    cards.add(new Card(8, Card.Suit.CLUBS));
    // Dewey
    // Hitting
    cards.add(new Card(6, Card.Suit.HEARTS));
    // Dealer
    // Hitting
    cards.add(new Card(3, Card.Suit.CLUBS));
    // Game G4 {5,5,5}: Huey 6+10+8 | You Q+7 | Dewey 10+3+6 | Dealer 6+8+4 >> Lose{5}, Lose{5}, Win{5}
    // Round 1
    // Huey
    cards.add(new Card(6, Card.Suit.HEARTS));
    // You
    cards.add(new Card(Card.QUEEN, Card.Suit.DIAMONDS));
    // Dewey
    cards.add(new Card(10, Card.Suit.HEARTS));
    // Dealer
    cards.add(new Card(6, Card.Suit.HEARTS));
    // Round 2
    // Huey
    cards.add(new Card(10, Card.Suit.HEARTS));
    // You
    cards.add(new Card(7, Card.Suit.SPADES));
    // Dewey
    cards.add(new Card(3, Card.Suit.HEARTS));
    // Dealer
    cards.add(new Card(8, Card.Suit.CLUBS));
    // Huey
    // Hitting
    cards.add(new Card(8, Card.Suit.HEARTS));
    // Dewey
    // Hitting
    cards.add(new Card(6, Card.Suit.DIAMONDS));
    // Dealer
    // Hitting
    cards.add(new Card(4, Card.Suit.SPADES));
    // Game G5 {5,5,5}: Huey A+10 | You Q+A | Dewey A+3+4 | Dealer 6+4+8 >> Win{5}, Win{5}, Push{5}
    // Round 1
    // Huey
    cards.add(new Card(Card.ACE, Card.Suit.HEARTS));
    // You
    cards.add(new Card(Card.QUEEN, Card.Suit.HEARTS));
    // Dewey
    cards.add(new Card(Card.ACE, Card.Suit.CLUBS));
    // Dealer
    cards.add(new Card(6, Card.Suit.HEARTS));
    // Round 2
    // Huey
    cards.add(new Card(10, Card.Suit.SPADES));
    // You
    cards.add(new Card(Card.ACE, Card.Suit.HEARTS));
    // Dewey
    cards.add(new Card(3, Card.Suit.CLUBS));
    // Dealer
    cards.add(new Card(4, Card.Suit.SPADES));
    // Dewey
    // Hitting
    cards.add(new Card(4, Card.Suit.HEARTS));
    // Dealer
    // Hitting
    cards.add(new Card(8, Card.Suit.SPADES));
    // Game G6 {5,5,5}: Huey 2+2+3+10 | You A+K | Dewey 10+5+8 | Dealer 10+7 >> Push{5}, Win{5}, Lose{5}
    // Round 1
    // Huey
    cards.add(new Card(2, Card.Suit.CLUBS));
    // You
    cards.add(new Card(Card.ACE, Card.Suit.DIAMONDS));
    // Dewey
    cards.add(new Card(10, Card.Suit.SPADES));
    // Dealer
    cards.add(new Card(10, Card.Suit.DIAMONDS));
    // Round 2
    // Huey
    cards.add(new Card(2, Card.Suit.DIAMONDS));
    // You
    cards.add(new Card(Card.KING, Card.Suit.CLUBS));
    // Dewey
    cards.add(new Card(5, Card.Suit.HEARTS));
    // Dealer
    cards.add(new Card(7, Card.Suit.HEARTS));
    // Huey
    // Hitting
    cards.add(new Card(3, Card.Suit.DIAMONDS));
    cards.add(new Card(10, Card.Suit.CLUBS));
    // Dewey
    // Hitting
    cards.add(new Card(8, Card.Suit.CLUBS));
  }
}
// END generated code
