//
// Code auto-generated by Ray.
// Thu Apr 02 14:15:18 EDT 2026
//
package charlie.sidebet.test;
import charlie.card.Card;

public class Shoe extends charlie.shoe.Shoe {
    @Override
    public void init() {
        cards.clear();
        // Game G1 {25}: You 7+9+3 | Dealer K+9 >> Push{25}
        // Round 1
        // You
        cards.add(new Card(7, Card.Suit.CLUBS));
        // Dealer
        cards.add(new Card(Card.KING, Card.Suit.DIAMONDS));
        // Round 2
        // You
        cards.add(new Card(9, Card.Suit.DIAMONDS));
        // Dealer
        cards.add(new Card(9, Card.Suit.SPADES));
        // You
        // Hitting
        cards.add(new Card(3, Card.Suit.SPADES));
        // Game G2 {25}: You 7+9+3 | Dealer Q+8 >> Win{25}
        // Round 1
        // You
        cards.add(new Card(7, Card.Suit.HEARTS));
        // Dealer
        cards.add(new Card(Card.QUEEN, Card.Suit.SPADES));
        // Round 2
        // You
        cards.add(new Card(9, Card.Suit.SPADES));
        // Dealer
        cards.add(new Card(8, Card.Suit.DIAMONDS));
        // You
        // Hitting
        cards.add(new Card(3, Card.Suit.SPADES));
        // Game G3 {25}: You 9+7+3 | Dealer K+8 >> Lose{25}
        // Round 1
        // You
        cards.add(new Card(9, Card.Suit.HEARTS));
        // Dealer
        cards.add(new Card(Card.KING, Card.Suit.SPADES));
        // Round 2
        // You
        cards.add(new Card(7, Card.Suit.CLUBS));
        // Dealer
        cards.add(new Card(8, Card.Suit.DIAMONDS));
        // You
        // Hitting
        cards.add(new Card(3, Card.Suit.SPADES));
        // Game G4 {25}: You 7+9+3 | Dealer Q+10 >> Lose{25}
        // Round 1
        // You
        cards.add(new Card(7, Card.Suit.CLUBS));
        // Dealer
        cards.add(new Card(Card.QUEEN, Card.Suit.CLUBS));
        // Round 2
        // You
        cards.add(new Card(9, Card.Suit.HEARTS));
        // Dealer
        cards.add(new Card(10, Card.Suit.SPADES));
        // You
        // Hitting
        cards.add(new Card(3, Card.Suit.CLUBS));
        // Game G5 {25}: You 9+7+3 | Dealer K+10 >> Lose{25}
        // Round 1
        // You
        cards.add(new Card(9, Card.Suit.DIAMONDS));
        // Dealer
        cards.add(new Card(Card.KING, Card.Suit.HEARTS));
        // Round 2
        // You
        cards.add(new Card(7, Card.Suit.HEARTS));
        // Dealer
        cards.add(new Card(10, Card.Suit.SPADES));
        // You
        // Hitting
        cards.add(new Card(3, Card.Suit.DIAMONDS));
        // Game G6 {25}: You KS+QS | Dealer Q+8 >> Win{25}
        // Round 1
        // You
        cards.add(new Card(Card.KING, Card.Suit.SPADES));
        // Dealer
        cards.add(new Card(Card.QUEEN, Card.Suit.HEARTS));
        // Round 2
        // You
        cards.add(new Card(Card.QUEEN, Card.Suit.SPADES));
        // Dealer
        cards.add(new Card(8, Card.Suit.CLUBS));
        // Game G7 {25}: You KD+QC | Dealer K+8 >> Win{25}
        // Round 1
        // You
        cards.add(new Card(Card.KING, Card.Suit.DIAMONDS));
        // Dealer
        cards.add(new Card(Card.KING, Card.Suit.SPADES));
        // Round 2
        // You
        cards.add(new Card(Card.QUEEN, Card.Suit.CLUBS));
        // Dealer
        cards.add(new Card(8, Card.Suit.HEARTS));
        // Game G8 {25}: You 8+5 | Dealer Q+6+K >> Win{25}
        // Round 1
        // You
        cards.add(new Card(8, Card.Suit.DIAMONDS));
        // Dealer
        cards.add(new Card(Card.QUEEN, Card.Suit.CLUBS));
        // Round 2
        // You
        cards.add(new Card(5, Card.Suit.SPADES));
        // Dealer
        cards.add(new Card(6, Card.Suit.DIAMONDS));
        // Dealer
        // Hitting
        cards.add(new Card(Card.KING, Card.Suit.CLUBS));
        // Game G9 {25}: You 7+6 | Dealer K+6+K >> Win{25}
        // Round 1
        // You
        cards.add(new Card(7, Card.Suit.CLUBS));
        // Dealer
        cards.add(new Card(Card.KING, Card.Suit.DIAMONDS));
        // Round 2
        // You
        cards.add(new Card(6, Card.Suit.CLUBS));
        // Dealer
        cards.add(new Card(6, Card.Suit.SPADES));
        // Dealer
        // Hitting
        cards.add(new Card(Card.KING, Card.Suit.DIAMONDS));
        // Game G10 {25}: You 6+8 | Dealer Q+6+K >> Win{25}
        // Round 1
        // You
        cards.add(new Card(6, Card.Suit.DIAMONDS));
        // Dealer
        cards.add(new Card(Card.QUEEN, Card.Suit.DIAMONDS));
        // Round 2
        // You
        cards.add(new Card(8, Card.Suit.DIAMONDS));
        // Dealer
        cards.add(new Card(6, Card.Suit.SPADES));
        // Dealer
        // Hitting
        cards.add(new Card(Card.KING, Card.Suit.CLUBS));
    }
}
// END generated code
